// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0--rc1
// source: agent_client.proto

package agent_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentClientService_StreamMessage_FullMethodName = "/proto.AgentClientService/StreamMessage"
)

// AgentClientServiceClient is the client API for AgentClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClientServiceClient interface {
	StreamMessage(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MessageCommand, MessageCommand], error)
}

type agentClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClientServiceClient(cc grpc.ClientConnInterface) AgentClientServiceClient {
	return &agentClientServiceClient{cc}
}

func (c *agentClientServiceClient) StreamMessage(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MessageCommand, MessageCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentClientService_ServiceDesc.Streams[0], AgentClientService_StreamMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MessageCommand, MessageCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentClientService_StreamMessageClient = grpc.BidiStreamingClient[MessageCommand, MessageCommand]

// AgentClientServiceServer is the server API for AgentClientService service.
// All implementations must embed UnimplementedAgentClientServiceServer
// for forward compatibility.
type AgentClientServiceServer interface {
	StreamMessage(grpc.BidiStreamingServer[MessageCommand, MessageCommand]) error
	mustEmbedUnimplementedAgentClientServiceServer()
}

// UnimplementedAgentClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentClientServiceServer struct{}

func (UnimplementedAgentClientServiceServer) StreamMessage(grpc.BidiStreamingServer[MessageCommand, MessageCommand]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMessage not implemented")
}
func (UnimplementedAgentClientServiceServer) mustEmbedUnimplementedAgentClientServiceServer() {}
func (UnimplementedAgentClientServiceServer) testEmbeddedByValue()                            {}

// UnsafeAgentClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentClientServiceServer will
// result in compilation errors.
type UnsafeAgentClientServiceServer interface {
	mustEmbedUnimplementedAgentClientServiceServer()
}

func RegisterAgentClientServiceServer(s grpc.ServiceRegistrar, srv AgentClientServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentClientService_ServiceDesc, srv)
}

func _AgentClientService_StreamMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentClientServiceServer).StreamMessage(&grpc.GenericServerStream[MessageCommand, MessageCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentClientService_StreamMessageServer = grpc.BidiStreamingServer[MessageCommand, MessageCommand]

// AgentClientService_ServiceDesc is the grpc.ServiceDesc for AgentClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AgentClientService",
	HandlerType: (*AgentClientServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessage",
			Handler:       _AgentClientService_StreamMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent_client.proto",
}
