// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0--rc1
// source: agent_client.proto

package agent_client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Cmd           string                 `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageCommand) Reset() {
	*x = MessageCommand{}
	mi := &file_agent_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCommand) ProtoMessage() {}

func (x *MessageCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCommand.ProtoReflect.Descriptor instead.
func (*MessageCommand) Descriptor() ([]byte, []int) {
	return file_agent_client_proto_rawDescGZIP(), []int{0}
}

func (x *MessageCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageCommand) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MessageCommand) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *MessageCommand) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_agent_client_proto protoreflect.FileDescriptor

const file_agent_client_proto_rawDesc = "" +
	"\n" +
	"\x12agent_client.proto\x12\x05proto\"Z\n" +
	"\x0eMessageCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03cmd\x18\x03 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data2a\n" +
	"\x15MessageCommandService\x12H\n" +
	"\x14StreamMessageCommand\x12\x15.proto.MessageCommand\x1a\x15.proto.MessageCommand(\x010\x01B\x11Z\x0f./;agent_clientb\x06proto3"

var (
	file_agent_client_proto_rawDescOnce sync.Once
	file_agent_client_proto_rawDescData []byte
)

func file_agent_client_proto_rawDescGZIP() []byte {
	file_agent_client_proto_rawDescOnce.Do(func() {
		file_agent_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_client_proto_rawDesc), len(file_agent_client_proto_rawDesc)))
	})
	return file_agent_client_proto_rawDescData
}

var file_agent_client_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_agent_client_proto_goTypes = []any{
	(*MessageCommand)(nil), // 0: proto.MessageCommand
}
var file_agent_client_proto_depIdxs = []int32{
	0, // 0: proto.MessageCommandService.StreamMessageCommand:input_type -> proto.MessageCommand
	0, // 1: proto.MessageCommandService.StreamMessageCommand:output_type -> proto.MessageCommand
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_client_proto_init() }
func file_agent_client_proto_init() {
	if File_agent_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_client_proto_rawDesc), len(file_agent_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_client_proto_goTypes,
		DependencyIndexes: file_agent_client_proto_depIdxs,
		MessageInfos:      file_agent_client_proto_msgTypes,
	}.Build()
	File_agent_client_proto = out.File
	file_agent_client_proto_goTypes = nil
	file_agent_client_proto_depIdxs = nil
}
